"""init tables

Revision ID: 9239aa2d281b
Revises:
Create Date: 2025-09-29 16:46:47.217186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9239aa2d281b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id"),
    )
    op.create_table(
        "errors",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("device_id", sa.String(length=100), nullable=True),
        sa.Column(
            "ts",
            sa.BigInteger(),
            server_default=sa.text("EXTRACT(EPOCH FROM NOW())::bigint"),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "telemetry",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("device_id", sa.String(length=100), nullable=False),
        sa.Column("ts", sa.BigInteger(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("humidity", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.device_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_telemetry_device_ts",
        "telemetry",
        ["device_id", "ts"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_telemetry_device_ts", table_name="telemetry", postgresql_using="btree"
    )
    op.drop_table("telemetry")
    op.drop_table("errors")
    op.drop_table("devices")
    # ### end Alembic commands ###
