name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  backend:
    name: Backend (lint & test)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: iot
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U dev -d iot"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
      mosquitto:
        image: eclipse-mosquitto:2
        ports:
          - 1883:1883
        options: >-
          --health-cmd="mosquitto -c /mosquitto-no-auth.conf -v || exit 0"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    env:
      # 讓 app 在 CI 用本機埠連 service
      DATABASE_URL: postgresql+psycopg://dev:dev@localhost:5432/iot
      MQTT_HOST: localhost
      MQTT_PORT: 1883
      ONLINE_GRACE_SECONDS: 120
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('server/requirements.txt', 'server/pyproject.toml', 'server/poetry.lock') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install deps (pip)
        if: hashFiles('server/requirements.txt') != ''
        working-directory: server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff black pre-commit

      - name: Install deps (pyproject)
        if: hashFiles('server/pyproject.toml') != ''
        working-directory: server
        run: |
          python -m pip install --upgrade pip
          pip install ".[all]" || true
          pip install pytest ruff black pre-commit

      - name: Lint (ruff + black --check)
        working-directory: server
        run: |
          ruff check .
          black --check .

      - name: Unit/Integration tests (pytest)
        working-directory: server
        run: |
          pytest -q

  frontend:
    name: Frontend (lint & build)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint
        run: |
          if npm run -q lint; then echo "lint ok"; else echo "no lint script, skip"; fi

      - name: Build
        env:
          VITE_API_URL: http://localhost:8000
        run: npm run build

  docker-build:
    name: Docker build (server)
    runs-on: ubuntu-latest
    needs: [backend]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t iot-server:ci -f server/Dockerfile .
